package com.ideals.arnav.ui

// i18n dictionary for the redesigned TrailSight screens. Strings cover the
// flows that have Compose implementations: library, preview sheet, AR chrome,
// resume cold-start, settings.
data class TrailSightStrings(
    // Library
    val appName: String,
    val routesCountTemplate: String, // "{n} routes · on this device"
    val noRoutes: String,
    val allRoutes: String,
    val dateAdded: String,
    val resumeLast: String,

    // Empty state
    val emptyTitle: String,
    val emptyBody: String,
    val uploadFile: String,
    val maxSizeHint: String, // "GPX  ·  KML  ·  max 5MB"

    // Delete confirm
    val deleteTitle: String,
    val deleteBody: String,
    val deleteAction: String,
    val cancel: String,

    // Preview
    val previewTrail: String,
    val distance: String,
    val climb: String,
    val waypoints: String,
    val elevation: String,
    val startAr: String,
    val holdPhoneHint: String,
    val routePreview: String,

    // AR chrome
    val exit: String,
    val hudNext: String,
    val hudRemaining: String,
    val hudEta: String,
    val offRouteLabel: String,

    // Resume
    val welcomeBack: String,
    val pickingUp: String,
    val resumeBody: String,
    val lastTrail: String,
    val continueTrail: String,
    val pickDifferent: String,

    // Settings
    val settings: String,
    val language: String,
    val languageNote: String,
    val navigation: String,
    val keepScreenOn: String,
    val showElevationProfile: String,
    val autoResume: String,
    val autoResumeSub: String,
    val about: String,
    val version: String,
    val storageUsed: String,
    val englishLabel: String,
    val englishSub: String,
    val hebrewLabel: String,
    val hebrewSub: String,

    // Onboarding
    val onboardingStep: String,        // "SETUP · STEP 2 OF 2"
    val onboardingBeta: String,        // "BETA"
    val onboardingTitle: String,       // "Two things before\nthe trail begins."
    val onboardingBody: String,
    val onboardingCameraTitle: String,
    val onboardingCameraSub: String,
    val onboardingLocationTitle: String,
    val onboardingLocationSub: String,
    val onboardingGranted: String,     // "GRANTED"
    val onboardingAsk: String,         // "ASK"
    val onboardingContinue: String,    // "Continue"
    val onboardingCoordsFooter: String,
)

private val EN = TrailSightStrings(
    appName = "TrailSight",
    routesCountTemplate = "{n} routes · on this device",
    noRoutes = "No routes yet",
    allRoutes = "ALL ROUTES",
    dateAdded = "Date added",
    resumeLast = "RESUME LAST TRAIL",
    emptyTitle = "Chart your first trail",
    emptyBody = "Upload a GPX or KML file and we'll light up the path ahead of you.",
    uploadFile = "Upload file",
    maxSizeHint = "GPX  ·  KML  ·  max 5MB",
    deleteTitle = "Delete this route?",
    deleteBody = "The file will be permanently removed from this device.",
    deleteAction = "Delete",
    cancel = "Cancel",
    previewTrail = "PREVIEW TRAIL",
    distance = "DISTANCE",
    climb = "CLIMB",
    waypoints = "WAYPOINTS",
    elevation = "ELEVATION",
    startAr = "Start AR navigation",
    holdPhoneHint = "Hold phone upright to see breadcrumbs",
    routePreview = "ROUTE PREVIEW",
    exit = "Exit",
    hudNext = "NEXT WAYPOINT",
    hudRemaining = "REMAINING",
    hudEta = "ETA",
    offRouteLabel = "OFF ROUTE · REROUTING",
    welcomeBack = "WELCOME BACK",
    pickingUp = "Picking up where\nyou left off",
    resumeBody = "Your last trail is ready — tap continue to jump back into AR navigation.",
    lastTrail = "● LAST TRAIL",
    continueTrail = "Continue trail",
    pickDifferent = "Choose a different route",
    settings = "Settings",
    language = "LANGUAGE",
    languageNote = "Interface follows the selected language. Layout flips for right-to-left scripts.",
    navigation = "NAVIGATION",
    keepScreenOn = "Keep screen on during AR",
    showElevationProfile = "Show elevation profile",
    autoResume = "Auto-resume last trail",
    autoResumeSub = "Open directly to the trail after reopening the app",
    about = "ABOUT",
    version = "Version",
    storageUsed = "Storage used",
    englishLabel = "English",
    englishSub = "English (US)",
    hebrewLabel = "עברית",
    hebrewSub = "Hebrew · עברית",
    onboardingStep = "SETUP · STEP 2 OF 2",
    onboardingBeta = "BETA",
    onboardingTitle = "Two things before\nthe trail begins.",
    onboardingBody = "We overlay waypoints on what your camera sees. Both permissions stay on your device.",
    onboardingCameraTitle = "Camera",
    onboardingCameraSub = "Paint breadcrumbs onto your view",
    onboardingLocationTitle = "Precise location",
    onboardingLocationSub = "Track progress along your route",
    onboardingGranted = "GRANTED",
    onboardingAsk = "ASK",
    onboardingContinue = "Continue",
    onboardingCoordsFooter = "N 32.072°  ·  E 34.785°  ·  ELEV 25M",
)

private val HE = TrailSightStrings(
    appName = "TrailSight",
    routesCountTemplate = "{n} מסלולים · במכשיר זה",
    noRoutes = "אין מסלולים עדיין",
    allRoutes = "כל המסלולים",
    dateAdded = "תאריך הוספה",
    resumeLast = "המשך מסלול אחרון",
    emptyTitle = "סמן את המסלול הראשון שלך",
    emptyBody = "העלה קובץ GPX או KML ואנו נאיר את הדרך שלפניך.",
    uploadFile = "העלה קובץ",
    maxSizeHint = "GPX  ·  KML  ·  מקס׳ 5MB",
    deleteTitle = "למחוק את המסלול?",
    deleteBody = "הקובץ יוסר לצמיתות מהמכשיר.",
    deleteAction = "מחק",
    cancel = "ביטול",
    previewTrail = "תצוגה מקדימה",
    distance = "מרחק",
    climb = "עלייה",
    waypoints = "נקודות",
    elevation = "גובה",
    startAr = "התחל ניווט AR",
    holdPhoneHint = "החזק את הטלפון זקוף כדי לראות סימונים",
    routePreview = "תצוגת מסלול",
    exit = "יציאה",
    hudNext = "הנקודה הבאה",
    hudRemaining = "נותרו",
    hudEta = "זמן משוער",
    offRouteLabel = "סטייה מהמסלול · מחשב מחדש",
    welcomeBack = "ברוך שובך",
    pickingUp = "ממשיכים מהמקום\nשבו עצרת",
    resumeBody = "המסלול האחרון שלך מוכן — הקש להמשך לניווט AR.",
    lastTrail = "● מסלול אחרון",
    continueTrail = "המשך מסלול",
    pickDifferent = "בחר מסלול אחר",
    settings = "הגדרות",
    language = "שפה",
    languageNote = "הממשק משתנה בהתאם לשפה הנבחרת. הפריסה מתהפכת עבור כתיבה מימין לשמאל.",
    navigation = "ניווט",
    keepScreenOn = "השאר מסך פעיל בזמן AR",
    showElevationProfile = "הצג פרופיל גובה",
    autoResume = "חידוש אוטומטי של המסלול",
    autoResumeSub = "פתיחה ישירות למסלול לאחר פתיחה מחדש",
    about = "אודות",
    version = "גרסה",
    storageUsed = "שטח אחסון",
    englishLabel = "English",
    englishSub = "English (US)",
    hebrewLabel = "עברית",
    hebrewSub = "Hebrew · עברית",
    onboardingStep = "התקנה · שלב 2 מתוך 2",
    onboardingBeta = "ביתא",
    onboardingTitle = "שני דברים לפני\nשהמסלול מתחיל.",
    onboardingBody = "אנו מציגים נקודות ציון על מה שהמצלמה רואה. שתי ההרשאות נשארות במכשיר שלך.",
    onboardingCameraTitle = "מצלמה",
    onboardingCameraSub = "שרטוט סימונים על שדה הראייה",
    onboardingLocationTitle = "מיקום מדויק",
    onboardingLocationSub = "מעקב אחר התקדמות במסלול",
    onboardingGranted = "אושר",
    onboardingAsk = "נדרש",
    onboardingContinue = "המשך",
    onboardingCoordsFooter = "N 32.072°  ·  E 34.785°  ·  ELEV 25M",
)

fun strings(lang: String): TrailSightStrings =
    if (lang == TrailSightSettings.LANG_HE) HE else EN
